-- Inserting New Drug

BEGIN
  APP_ADMIN.insert_drug(
    p_drug_name             => 'Cetirizine',
    p_expiry_date           => TO_DATE('2026-05-01', 'YYYY-MM-DD'),
    p_mrp                   => 75,
    p_price                 => 60,
    p_stock_quantity        => 150,
    p_suppliers_supplier_id => 5,   -- make sure this ID exists in SUPPLIERS
    p_catagory_catagory_id  => 1,    -- make sure this ID exists in CATAGORY
    p_created_by            => 1       
  );
END;
/

--
--Batch number is autogenerated inside the procedure using SYSTIMESTAMP.
--
--If Cetirizine already exists, it will update the stock, price, expiry, etc.
--
--If the drug name does not exist, it will insert a new row.
--
--The procedure also includes:
--
--validation for MRP ≥ price
--
--expiry_date > SYSDATE
--
--supplier and category existence check