DROP SEQUENCE drugs_seq;
CREATE SEQUENCE drugs_seq
  START WITH 100
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

DROP SEQUENCE catagory_seq;
CREATE SEQUENCE catagory_seq
  START WITH 100
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

DROP SEQUENCE doctors_seq;
CREATE SEQUENCE doctors_seq
  START WITH 100
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;


DROP SEQUENCE inventory_logs_seq;
CREATE SEQUENCE inventory_logs_seq
  START WITH 100
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

DROP SEQUENCE patients_seq;
CREATE SEQUENCE patients_seq
  START WITH 100
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

DROP SEQUENCE payment_method_seq;
CREATE SEQUENCE payment_method_seq
  START WITH 100
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

DROP SEQUENCE prescription_drugs_seq;
CREATE SEQUENCE prescription_drugs_seq
  START WITH 100
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

DROP SEQUENCE prescriptions_seq;
CREATE SEQUENCE prescriptions_seq
  START WITH 100
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

DROP SEQUENCE sales_transactions_seq;
CREATE SEQUENCE sales_transactions_seq
  START WITH 100
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

DROP SEQUENCE suppliers_seq;
CREATE SEQUENCE suppliers_seq
  START WITH 100
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

DROP SEQUENCE users_seq;  
CREATE SEQUENCE users_seq
  START WITH 100
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  

